/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ODZnPmd1374
 */
import { Button } from "@/components/ui/button"
import { CardContent, Card, CardTitle, CardHeader } from "@/components/ui/card"
import Link from "next/link"

export function LeagueDashboard() {
  return (
    <div className="grid gap-4 md:gap-8 lg:gap-12 xl:gap-16">
      <div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between md:gap-4 lg:gap-6">
        <div className="flex items-center gap-2 text-2xl font-semibold md:gap-1">
          <AwardIcon className="w-6 h-6" />
          <h1 className="text-3xl font-bold tracking-tighter">Pickem Pool</h1>
        </div>
        <div className="flex items-center gap-2 text-sm font-medium md:gap-4">
          <div className="flex items-center gap-1">
            <UserIcon className="w-4 h-4" />
            <span className="font-semibold">You</span>
          </div>
          <Button className="rounded-full" size="icon" variant="ghost">
            <LogOutIcon className="w-4 h-4" />
            <span className="sr-only">Log out</span>
          </Button>
        </div>
      </div>
      <Card className="p-0">
        <CardContent className="p-0">
          <div className="grid w-full grid-cols-1 items-stretch md:grid-cols-4">
            <div className="flex flex-col items-center justify-center p-4 text-center md:items-start md:justify-start md:p-6 md:gap-2 lg:gap-4">
              <div className="flex items-center gap-2 text-2xl font-semibold md:gap-1">
                <AwardIcon className="w-6 h-6" />
                <h2 className="text-3xl font-bold tracking-tighter">College Cup</h2>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">You are 3rd in this league</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">2 weeks remaining</p>
            </div>
            <div className="mx-auto flex w-full items-center justify-center p-4 md:p-6">
              <img
                alt="League image"
                className="rounded-full object-cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
            </div>
            <div className="grid w-full grid-cols-1 items-stretch gap-1 p-4 text-center md:grid-cols-2 md:gap-2 md:p-6 lg:gap-4">
              <div className="flex flex-col items-center justify-center gap-1 md:items-start md:justify-start md:gap-0">
                <h3 className="text-lg font-bold">Week 1</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Aug 28</p>
                <div className="relative w-full h-2 bg-gray-200 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-blue-500"
                    style={{
                      width: "25%",
                    }}
                  />
                </div>
              </div>
              <div className="flex flex-col items-center justify-center gap-1 md:items-start md:justify-start md:gap-0">
                <h3 className="text-lg font-bold">Week 2</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Sep 4</p>
                <div className="relative w-full h-2 bg-gray-200 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-blue-500"
                    style={{
                      width: "50%",
                    }}
                  />
                </div>
              </div>
              <div className="flex flex-col items-center justify-center gap-1 md:items-start md:justify-start md:gap-0">
                <h3 className="text-lg font-bold">Week 3</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Sep 11</p>
                <div className="relative w-full h-2 bg-gray-200 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-blue-500"
                    style={{
                      width: "75%",
                    }}
                  />
                </div>
              </div>
              <div className="flex flex-col items-center justify-center gap-1 md:items-start md:justify-start md:gap-0">
                <h3 className="text-lg font-bold">Week 4</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Sep 18</p>
                <div className="relative w-full h-2 bg-gray-200 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-blue-500"
                    style={{
                      width: "100%",
                    }}
                  />
                </div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
          <CardTitle className="text-sm font-medium">Leaderboard</CardTitle>
          <Link className="text-sm font-medium" href="#">
            View all
          </Link>
        </CardHeader>
        <CardContent className="p-0">
          <div className="space-y-1">
            <div className="grid w-full grid-cols-3 items-center gap-2 p-2">
              <div className="flex items-center gap-2">
                <span className="font-semibold">1.</span>
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
              </div>
              <div className="flex items-center gap-2 text-sm">
                <span className="font-semibold">2.</span>
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
              </div>
              <div className="flex items-center gap-2 text-sm">
                <span className="font-semibold">3.</span>
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
              </div>
            </div>
            <div className="grid w-full grid-cols-3 items-center gap-2 p-2">
              <div className="flex items-center gap-2">
                <span className="font-semibold">4.</span>
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
              </div>
              <div className="flex items-center gap-2 text-sm">
                <span className="font-semibold">5.</span>
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
              </div>
              <div className="flex items-center gap-2 text-sm">
                <span className="font-semibold">6.</span>
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}


function AwardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="8" r="6" />
      <path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function LogOutIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>
  )
}
