// Automatically generated by astro-icon
// eaca42b096f54bcfc5b7acb2f196f941e85542d79e08ebf0ad70ca461b25b06f

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "account"
		| "logo"
		| "logo-round"
		| "ribbon";
}