/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qV7y4dZ6vS9
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";

export default function Page() {
  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <h1 className="text-3xl font-bold">College Football Pick'em Pool</h1>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="league-name">League name</Label>
          <Input id="league-name" placeholder="Enter the league name" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="description">Description</Label>
          <Input id="description" placeholder="Enter the description" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="password">Password</Label>
          <Input id="password" placeholder="Optional" type="password" />
          <p className="text-xs text-gray-500 dark:text-gray-400">
            Password protected leagues are only accessible with the correct
            password.
          </p>
        </div>
        <Button className="w-full">Create League</Button>
      </div>
      <Separator className="my-8" />
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-bold">League Name</h2>
            <p className="text-sm leading-none text-gray-500 dark:text-gray-400">
              Description of the league
            </p>
          </div>
          <Button size="sm">Join</Button>
        </div>
        <div className="border-t border-gray-200 dark:border-gray-800" />
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-bold">League Name</h2>
            <p className="text-sm leading-none text-gray-500 dark:text-gray-400">
              Description of the league
            </p>
          </div>
          <Button size="sm">Join</Button>
        </div>
        <div className="border-t border-gray-200 dark:border-gray-800" />
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-bold">League Name</h2>
            <p className="text-sm leading-none text-gray-500 dark:text-gray-400">
              Description of the league
            </p>
          </div>
          <Button size="sm">Join</Button>
        </div>
        <div className="border-t border-gray-200 dark:border-gray-800" />
      </div>
    </div>
  );
}
